name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Node ${{ matrix.nodejs }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
    strategy:
      matrix:
        nodejs: [14, 16, "lts/*"]
        os: [
          ubuntu-latest, 
          windows-latest, 
          # macos-latest
        ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install and link
      run: yarn install --frozen-lockfile

    # - name: Test
    #   run: yarn test